[package]
name = "transaction_processor"
version = "1.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
uuid = { version = "1.17.0", features = ["v4"] }
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
